server:
  port: 8000
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    
spreadsheetwriter:
  auth:
    host: localhost
    port: 34533
  credentials:
    filepath: /home/nikolai/credentials.json
  user:
    nikolai.dueck@googlemail.com    
